### ISSUE TITLE
Never finds peers using Bugout.js

### ISSUE THREAD

**Issue by hhff** [draeder/p2p-tracker#2]
Hi Draeder!

Thank you so much for this. I left a note here: https://github.com/chr15m/bugout/issues/43#issuecomment-815294047

But felt it might make more sense to open the discussion here instead.

When I use this code:
```
var b = new Bugout("foo.bar", {"announce": ["wss://my-deployment.herokuapp.com"]});
```

My Bugout instance never finds any peers. Remove the "announce" option, (and refreshing until I actually do get a connection to `wss://hub.bugout.link`) does work as expected.

Am I missing any steps you took to get this working on your end? :)

**Comment by draeder** [comment]
@hhff There really shouldn't be any steps other than deploying the instance to Heroku using the deploy button, then using the app URL as your tracker in Bugout. Are you seeing the start message in the Heroku logging when a client tries to connect? If not, it means that your Bugout announcement is never making it to the tracker server.

**Comment by draeder** [comment]
@hhff I just tested my instance of p2p tracker in Heroku with Bugout and everything seems to be working. 

Just to be clear, you are launching your code with the bugout identifier twice, correct (e.g. if using the browser, you'd have two browser tabs; if using node.js, you'd have two node servers running [or one node server with one browser session]? Remember that your first instance is the announcement that there is a bugout instance available, the second instance finds that bugout instance and connects peers through the tracker.

In the Heroku logs for your p2p-tracker deployment you should see something similar to this, for each session:

```
2021-04-07T23:16:48.118348+00:00 app[web.1]: got start message from 2d5757303030372d2f487930744e387964446a6d
2021-04-07T23:16:56.852794+00:00 app[web.1]: got start message from 2d5757303030372d716b664478484d6e4d4f634e
```

**Comment by hhff** [comment]
Hi @draeder thank you so much for the fast response!

I just tested this a second time, and magically, it's now working. Not sure what was the issue the first time around, but anyhow, thank you for this!
