### ISSUE TITLE
Tracker only works on HTTP not HTTPS.

### ISSUE THREAD

**Issue by RyanSacks** [draeder/p2p-tracker#4]
Hi,
We're using this Tracker in our app, combined with Novage's P2P Media Loader Demo:
[https://github.com/Novage/p2p-media-loader](https://github.com/Novage/p2p-media-loader)

We downloaded the Demo, changed the default Tracker to one that we created and deployed it online.
The problem is it only works on HTTP (WS) not HTTPS (WSS). How can we get it working on HTTPS? What are the steps?

**Comment by draeder** [comment]
Thanks for the report.  I created this library to make 1-click deploys to Heroku or Glitch super-simple. By deploying to either of these services, SSL is enabled by default. You may be interested in the official [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker) library which this repo comes from.

**Comment by draeder** [comment]
Closing as there has been no further activity
